server.port: 8080

solon:
  debug: 1
  app:
    name: 'demo-app'
    group: 'demo'

# 记录器级别的配置示例
solon.logging.logger:
  "root": #默认记录器配置
    level: debug
  "com.zaxxer.hikari":
    level: info

redis:
  server: localhost:6379
  db: 1

postgres.db:
  jdbcUrl: jdbc:postgresql://localhost:5432/poem-solon?currentSchema=demo
  driverClassName: org.postgresql.Driver
  username: postgres
  password: 123
  connection-timeout: 10000
  validation-timeout: 3000
  idle-timeout: 60000
  max-lifetime: 60000
  maximum-pool-size: 10
  minimum-idle: 5
  read-only: false

# 配置数据源对应的 我给你找出那个文档mybatis 信息（要与 DataSource bean 的名字对上）这个是solon的官网提供的而应该是没错上面的pgsql
mybatis.db:
  typeAliases:    #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    - "cn.poem.solon.**.domain.entity"
  mappers:        #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）//支持 ** 或 * 占位符
    - "cn.poem.solon.system.mapper.*"
    - "classpath:mapper/*.xml"
  configuration: #扩展配置（要与 FlexConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapperVerifyEnabled: false #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true
  globalConfig: #全局配置（要与 FlexGlobalConfig 类的属性一一对应）//只是示例，别照抄
    printBanner: true
    keyConfig:
      keyType: "Generator"
      value: "snowFlakeId"

# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期:2小时
  timeout: 7200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: true

solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
  dateAsTimeZone: 'GMT+8' #配置时区
  dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
  longAsString: true #将long型转为字符串输出 （默认为false）
  boolAsInt: false   #将bool型转为字符串输出 （默认为false）
  nullStringAsEmpty: false
  nullBoolAsFalse: false
  nullNumberAsZero: false
  nullArrayAsEmpty: false
  nullAsWriteable: false
  enumAsName: false #枚举使用名字（v2.2.1 后支持）


knife4j:
  enable: true
  basic:
    enable: true
    username: admin
    password: 123456
  setting:
    enableOpenApi: true
    enableSwaggerModels: true
    enableFooter: true